# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Academic interests
    url: '#academia'
    weight: 20
  - name: Work experience
    url: '#experience'
    weight: 30
  # - name: Other interests
  #   url: '#other'
  #   weight: 40
  - name: Personal interests
    url: '#personal'
    weight: 40
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  # - name: Projects
  #   url: '#projects'
  #   weight: 30
  # - name: Talks
  #   url: '#talks'
  #   weight: 40
  # - name: Publications
  #   url: '#featured'
  #   weight: 50
  # - name: Contact
  #   url: '#contact'
  #   weight: 60
  - name: Resume
    url: 'uploads/CV_Wagner_(general).pdf'
    weight: 60
